name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.20.5

      - name: Go Mod Tidy
        run: go mod tidy

      - name: Run Tests
        run: go test --cover github.com/pintjuk/routemaster/src/route

      - name: Autotag
        uses: phish108/autotag-action@v1.1.64