name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Tests
    strategy:
      fail-fast: true
      matrix:
        os: [ "windows-latest", "ubuntu-latest", "macOS-latest" ]
        go: ["1.20.x"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - uses: WillAbides/setup-go-faster@v1.7.0
      with:
       go-version: ${{ matrix.go }}
    - run: "go test ./..."
    - run: "go vet ./..."
    - uses: dominikh/staticcheck-action@v1.2.0
      with:
        version: "2022.1.1"
        install-go: false
        cache-key: ${{ matrix.go }}
  tag:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 12
    steps:
      - uses: phish108/autotag-action@v1.1.55
        with:
          github-token: ${{ secrets.GITHUB_TOKEN}}